using System.Collections.Generic;
using Content.Client.Administration.Managers;
using Content.Client.Audio;
using Content.Client.Options.UI;
using Content.Shared.CCVar;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Localization;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AudioTab : Control
{
    [Dependency] private IAudioManager _audio = default!;
    [Dependency] private IClientAdminManager _admin = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    public AudioTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var masterVolume = Control.AddOptionPercentSlider(
            CVars.AudioMasterVolume,
            SliderVolumeMaster,
            scale: ContentAudioSystem.MasterVolumeMultiplier);
        masterVolume.ImmediateValueChanged += OnMasterVolumeSliderChanged;

        Control.AddOptionPercentSlider(
            CVars.MidiVolume,
            SliderVolumeMidi,
            scale: ContentAudioSystem.MidiVolumeMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbientMusicVolume,
            SliderVolumeAmbientMusic,
            scale: ContentAudioSystem.AmbientMusicMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbienceVolume,
            SliderVolumeAmbience,
            scale: ContentAudioSystem.AmbienceMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.LobbyMusicVolume,
            SliderVolumeLobby,
            scale: ContentAudioSystem.LobbyMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.InterfaceVolume,
            SliderVolumeInterface,
            scale: ContentAudioSystem.InterfaceMultiplier);

        Control.AddOptionSlider(
            CCVars.MaxAmbientSources,
            SliderMaxAmbienceSounds,
            _cfg.GetCVar(CCVars.MinMaxAmbientSourcesConfigured),
            _cfg.GetCVar(CCVars.MaxMaxAmbientSourcesConfigured));

        Control.AddOptionCheckBox(CCVars.LobbyMusicEnabled, LobbyMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.RestartSoundsEnabled, RestartSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.EventMusicEnabled, EventMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.AdminSoundsEnabled, AdminSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.BwoinkSoundEnabled, BwoinkSoundCheckBox);

        // Proximity voice chat.
        Control.AddOptionCheckBox(CCVars.VoiceInputEnabled, VoiceEnabledCheckBox);
        Control.AddOptionPercentSlider(CCVars.VoiceVolume, SliderVolumeVoice);
        // Mic input gain can be boosted above 100%, so allow up to 200%.
        Control.AddOptionPercentSlider(CCVars.VoiceInputVolume, SliderVolumeVoiceInput, max: 2f);

        // Microphone selection. Empty value = system default. Applies the next time the player talks.
        var inputDevices = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new(string.Empty, Loc.GetString("ui-options-audio-device-default")),
        };
        foreach (var device in _audio.GetAudioInputDevices())
        {
            inputDevices.Add(new OptionDropDownCVar<string>.ValueOption(device, device));
        }
        Control.AddOptionDropDown(CCVars.VoiceInputDevice, VoiceInputDeviceDropDown, inputDevices);

        // Output device for ALL game audio. Empty value = system default. Applied on next launch.
        var outputDevices = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new(string.Empty, Loc.GetString("ui-options-audio-device-default")),
        };
        foreach (var device in _audio.GetAudioOutputDevices())
        {
            outputDevices.Add(new OptionDropDownCVar<string>.ValueOption(device, device));
        }
        Control.AddOptionDropDown(CVars.AudioDevice, AudioOutputDeviceDropDown, outputDevices);

        Control.Initialize();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _admin.AdminStatusUpdated += UpdateAdminButtonsVisibility;
        UpdateAdminButtonsVisibility();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _admin.AdminStatusUpdated -= UpdateAdminButtonsVisibility;
    }


    private void UpdateAdminButtonsVisibility()
    {
        BwoinkSoundCheckBox.Visible = _admin.IsActive();
    }

    private void OnMasterVolumeSliderChanged(float value)
    {
        // TODO: I was thinking of giving OptionsTabControlRow a flag to "set CVar immediately", but I'm deferring that
        // until there's a proper system for enforcing people don't close the window with pending changes.
        _audio.SetMasterGain(value);
    }
}
