using Content.Client.UserInterface.Controls;
using Content.Shared.Xenoarchaeology.Equipment;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.Xenoarchaeology.Ui;

[GenerateTypedNameReferences]
public sealed partial class PeerReviewConsoleWindow : DefaultWindow
{
    private static readonly SpriteSpecifier.Rsi StoredDataSprite =
        new(new ResPath("Objects/Misc/bureaucracy.rsi"), "paper_dotmatrix_words");

    private static readonly SpriteSpecifier.Rsi MinorPublicationSprite =
        new(new ResPath("Objects/Misc/bureaucracy.rsi"), "paper");

    private static readonly SpriteSpecifier.Rsi SignificantPublicationSprite =
        new(new ResPath("Objects/Misc/bureaucracy.rsi"), "paper_words");

    private static readonly SpriteSpecifier.Rsi MajorPublicationSprite =
        new(new ResPath("Objects/Misc/bureaucracy.rsi"), "acquisition_form_words");

    public event Action<PublicationTier>? PublishRequested;

    public PeerReviewConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        StoredDataIcon.SetFromSpriteSpecifier(StoredDataSprite);
        MinorPublicationIcon.SetFromSpriteSpecifier(MinorPublicationSprite);
        SignificantPublicationIcon.SetFromSpriteSpecifier(SignificantPublicationSprite);
        MajorPublicationIcon.SetFromSpriteSpecifier(MajorPublicationSprite);

        HeaderPanel.PanelOverride = CreatePanel("#18372B");
        StoredDataPanel.PanelOverride = CreatePanel("#203D31");

        MinorPublicationPanel.PanelOverride = CreatePanel("#26372F");
        SignificantPublicationPanel.PanelOverride = CreatePanel("#294236");
        MajorPublicationPanel.PanelOverride = CreatePanel("#2D4B3B");

        PublishSmallButton.OnPressed += _ =>
            PublishRequested?.Invoke(PublicationTier.Small);

        PublishMediumButton.OnPressed += _ =>
            PublishRequested?.Invoke(PublicationTier.Medium);

        PublishLargeButton.OnPressed += _ =>
            PublishRequested?.Invoke(PublicationTier.Large);
    }

    public void UpdateState(PeerReviewConsoleUiState state)
    {
        StoredValueLabel.Text = $"{state.StoredValue} units";

        StoredStatusLabel.Text = state.StoredValue switch
        {
            >= PeerReviewConsoleConstants.LargePublicationCost =>
                "Major publication available",

            >= PeerReviewConsoleConstants.MediumPublicationCost =>
                "Significant publication available",

            >= PeerReviewConsoleConstants.SmallPublicationCost =>
                "Minor publication available",

            _ => "Awaiting additional submitted findings",
        };

        PublishSmallButton.Disabled =
            state.StoredValue <
            PeerReviewConsoleConstants.SmallPublicationCost;

        PublishMediumButton.Disabled =
            state.StoredValue <
            PeerReviewConsoleConstants.MediumPublicationCost;

        PublishLargeButton.Disabled =
            state.StoredValue <
            PeerReviewConsoleConstants.LargePublicationCost;
    }

    private static StyleBoxFlat CreatePanel(string color)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(color),
        };
    }
}
