using Content.Shared.Xenoarchaeology.Equipment;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Xenoarchaeology.Ui;

[GenerateTypedNameReferences]
public sealed partial class PeerReviewConsoleWindow : DefaultWindow
{
    public event Action<PublicationTier>? PublishRequested;

    public PeerReviewConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        PublishSmallButton.OnPressed += _ =>
            PublishRequested?.Invoke(PublicationTier.Small);

        PublishMediumButton.OnPressed += _ =>
            PublishRequested?.Invoke(PublicationTier.Medium);

        PublishLargeButton.OnPressed += _ =>
            PublishRequested?.Invoke(PublicationTier.Large);
    }

    public void UpdateState(PeerReviewConsoleUiState state)
    {
        StoredValueLabel.Text =
            $"Stored research data: {state.StoredValue}";

        PublishSmallButton.Disabled =
            state.StoredValue <
            PeerReviewConsoleConstants.SmallPublicationCost;

        PublishMediumButton.Disabled =
            state.StoredValue <
            PeerReviewConsoleConstants.MediumPublicationCost;

        PublishLargeButton.Disabled =
            state.StoredValue <
            PeerReviewConsoleConstants.LargePublicationCost;
    }
}
